name: Renovate
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * 6' # weekly; 08:00 at Saturday

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest

    if: github.repository == 'cert-manager/makefile-modules'

    permissions:
      id-token: write

    steps:
      - name: Fail if branch is not head of branch.
        if: ${{ !startsWith(github.ref, 'refs/heads/') && env.SOURCE_BRANCH != '' && env.SELF_UPGRADE_BRANCH != '' }}
        run: |
          echo "This workflow should not be run on a non-branch-head."
          exit 1

      - name: Octo STS Token Exchange
        uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: cert-manager/makefile-modules
          identity: renovate

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        # Adding `fetch-depth: 0` makes sure tags are also fetched. We need
        # the tags so `git describe` returns a valid version.
        # see https://github.com/actions/checkout/issues/701 for extra info about this option
        with:
          fetch-depth: 0
          token: ${{ steps.octo-sts.outputs.token }}

      - id: go-version
        run: |
          make print-go-version >> "$GITHUB_OUTPUT"

      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ steps.go-version.outputs.result }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@c91a61c730fa166439cd3e2c300c041590002b1d # v44.0.3
        with:
          configurationFile: .github/renovate.json5
          token: ${{ steps.octo-sts.outputs.token }}
        env:
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM: "github"
          LOG_LEVEL: "debug"
          RENOVATE_ALLOWED_COMMANDS: '[".*"]'
